### ISSUE TITLE
[REFAC] 내부 코드 리팩토링 

### ISSUE THREAD

**Issue by minseungseon** [minseungseon/cau_teampang_web#12]
1. 대학교 이름 CHOICE 수정
CHOICE 사용은 너무 커지면 힘들다. 
textfield로 받아도 됨 
그리고 validation을 만들어서 따로 추가해도됨 
'중앙대'가 아니라 '중앙대학교'라고 쓰도록 하거나… 
성별은 CHOICE 괜찮음.

2. PermissionMixin 확인
누구나 다 가입을 할 수 있느냐, 어떻게 제한을 줄 수 있는 것
쓸지 말지에 대해서 생각해볼 것, 슬랙에 공유하기
--> 이번주에 한번 백엔드 공유 세션

**Comment by sanggae4133** [comment]
해결했습니다!
